# Generated by Django 2.2.5 on 2019-09-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0002_auto_20190918_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='years_old',
            field=models.CharField(max_length=40),
        ),
    ]
